{
    "Success" : 0, 
    "Operation not permitted" : 1,
    "No such file or directory" : 2,
    "No such process" : 3,
    "Interrupted system call" : 4,
    "I/O error" : 5,
    "No such device or address" : 6,
    "Argument list too long" : 7,
    "Exec format error" : 8,
    "Bad file number" : 9,
    "No child processes" : 10,
    "Try again" : 11,
    "Out of resources" : 12,
    "Permission denied" : 13,
    "Bad address" : 14,
    "Block device required" : 15,
    "Device or resource busy" : 16,
    "File exists" : 17,
    "End of file" : 18,
    "Cross-device link" : 19,
    "No such device" : 20,
    "Not a directory" : 21,
    "Is a directory" : 22,
    "Invalid argument" : 23,
    "File table overflow" : 24,
    "Too many open files" : 25,
    "Not a typewriter" : 26,
    "Text file busy" : 27,
    "File too large" : 28,
    "No space left on device" : 29,
    "Illegal seek" : 30,
    "Read-only file system" : 31,
    "Too many links" : 32,
    "Broken pipe" : 33,
    "Math argument out of domain of func" : 34,
    "Math result not representable" : 35,
    "Resource deadlock would occur" : 36,
    "File name too long" : 37,
    "No record locks available" : 38,
    "Function not implemented" : 39,
    "Directory not empty" : 40,
    "Too many symbolic links encountered" : 41,
    "No message of desired type" : 42,
    "Identifier removed" : 43,
    "Channel number out of range" : 44,
    "Level 2 not synchronized" : 45,
    "Level 3 halted" : 46,
    "Level 3 reset" : 47,
    "Link number out of range" : 48,
    "Protocol driver not attached" : 49,
    "No CSI structure available" : 50,
    "Level 2 halted" : 51,
    "Invalid exchange" : 52,
    "Invalid request descriptor" : 53,
    "Exchange full" : 54,
    "No anode" : 55,
    "Invalid request code" : 56,
    "Invalid slot" : 57,
    "Bad font file format" : 58,
    "Device not a stream" : 59,
    "No data available" : 60,
    "Timer expired" : 61,
    "Out of streams resources" : 62,
    "Machine is not on the network" : 63,
    "Package not installed" : 64,
    "Object is remote" : 65,
    "Link has been severed" : 66,
    "Advertise error" : 67,
    "Srmount error" : 68,
    "Communication error on send" : 69,
    "Protocol error" : 70,
    "Multihop attempted" : 71,
    "RFS specific error" : 72,
    "Not a data message" : 73,
    "Value too large for defined data type" : 74,
    "Name not unique on network" : 75,
    "File descriptor in bad state" : 76,
    "Remote address changed" : 77,
    "Can not access a needed shared library" : 78,
    "Accessing a corrupted shared library" : 79,
    ".lib section in a.out corrupted" : 80,
    "Attempting to link in too many shared libraries" : 81,
    "Cannot exec a shared library directly" : 82,
    "Illegal byte sequence" : 83,
    "Interrupted system call should be restarted" : 84,
    "Streams pipe error" : 85,
    "Too many users" : 86,
    "Socket operation on non-socket" : 87,
    "Destination address required" : 88,
    "Message too long" : 89,
    "Protocol wrong type for socket" : 90,
    "Protocol not available" : 91,
    "Protocol not supported" : 92,
    "Socket type not supported" : 93,
    "Operation not supported on transport endpoint" : 94,
    "Protocol family not supported" : 95,
    "Address family not supported by protocol" : 96,
    "Address already in use" : 97,
    "Cannot assign requested address" : 98,
    "Network is down" : 99,
    "Network is unreachable" : 100,
    "Network dropped connection because of reset" : 101,
    "Software caused connection abort" : 102,
    "Connection reset by peer" : 103,
    "No buffer space available" : 104,
    "Transport endpoint is already connected" : 105,
    "Transport endpoint is not connected" : 106,
    "Cannot send after transport endpoint shutdown" : 107,
    "Too many references: cannot splice" : 108,
    "Connection timed out" : 109,
    "Connection refused" : 110,
    "Host is down" : 111,
    "No route to host" : 112,
    "Operation already in progress" : 113,
    "Operation now in progress" : 114,
    "Stale NFS file handle" : 115,
    "Structure needs cleaning" : 116,
    "Not a XENIX named type file" : 117,
    "No XENIX semaphores available" : 118,
    "Is a named type file" : 119,
    "Remote I/O error" : 120,
    "Quota exceeded" : 121,
    "No medium found" : 122,
    "Wrong medium type" : 123,
    "Operation Canceled" : 124,
    "Required key not available" : 125,
    "Key has expired" : 126,
    "Key has been revoked" : 127,
    "Key was rejected by service" : 128,
    "Owner died" : 129,
    "State not recoverable" : 130,
    "Operation not possible due to RF-kill" : 131,
    "Memory page has hardware error" : 132,
    "Output truncated" : 133,
    "Not implemented" : 134,
    "Unknown error" : 135,
    "msgLib delete() failed" : 136,
    "thrCreate() failed" : 137,
    "Thread was aborted" : 138,
    "libConfig open() failed" : 139,
    "libConfig seek failed" : 140,
    "libConfig flash open() failed" : 141,
    "libConfig flash lseek failed" : 142,
    "libConfig configDelete() failed" : 143,
    "Incorrect params to UsrNodeMain" : 144,
    "Unicode strings are not supported by this function" : 145,
    "Invalid value for ai_flags field" : 146,
    "NAME or SERVICE is unknown" : 147,
    "Non-recoverable failure in name resolution" : 148,
    "SERVICE not supported for socket type" : 149,
    "No address associated with NAME" : 150,
    "Address family for NAME not supported" : 151,
    "Request not canceled" : 152,
    "All requests done" : 153,
    "IDN encoding failed" : 154,
    "Last page" : 155,
    "More data to follow. Not end of stream" : 156,
    "Command not found" : 157,
    "Error parsing command" : 158,
    "Sched queue length exceeded" : 159,
    "Failure in the message layer" : 160,
    "Out of messages" : 161,
    "Shutdown message" : 162,
    "No such node exists in cluster" : 163,
    "New table created" : 164,
    "No such result set" : 165,
    "Data format does not support appending fields" : 166,
    "Data format does not support removing fields" : 167,
    "Failed to parse data format value" : 168,
    "Record data format is corrupt" : 169,
    "Field does not exist within record" : 170,
    "Unknown field type" : 171,
    "Failed to find a record corresponding to the given record number" : 172,
    "Searched value was not found" : 173,
    "Invalid data format" : 174,
    "Context does not support dereferencing a remote Fatptr" : 175,
    "Values buffer is too small to store even a single field value" : 176,
    "Too many values discovered for a single field" : 177,
    "Field type is not supported in this format" : 178,
    "Maximum number of dictionary segments reached" : 179,
    "Bad record identifier" : 180,
    "System has exceeded the configured maximum number of records; try increasing Constants.DfMaxRecords" : 181,
    "Type mismatch during index creation" : 182,
    "Intended key has more than a single" : 183,
    "Dataset not found" : 184,
    "Loading of this dataset has already started" : 185,
    "URL length is too large" : 186,
    "URL is not valid" : 187,
    "Data source type does not support file creation" : 188,
    "Data source type does not support file deletion" : 189,
    "Data source type does not support file rename" : 190,
    "Data source type does not support writing" : 191,
    "Data source type does not support seeking" : 192,
    "Seek failed" : 193,
    "Data source type does not support directory creation" : 194,
    "Data source type does not support directory removal" : 195,
    "Loading of this dataset failed" : 196,
    "Dataset is in use" : 197,
    "Data source does not support specified data format type" : 198,
    "Failed to initialize the mysql client library" : 199,
    "Failed to connect to mysql server & database" : 200,
    "Failed to run query against mysql table" : 201,
    "Failed to connect to the specified Data Source Name" : 202,
    "Failed to cleanup an internal nested error" : 203,
    "ODBC based database connections must be created outside of Xcalar" : 204,
    "Failed to bind variable to ODBC parameter" : 205,
    "Failed to create ODBC table" : 206,
    "Failed to export record to ODBC table" : 207,
    "Export table already exists" : 208,
    "Export table does not exist" : 209,
    "A target was added while targets were being listed" : 210,
    "The requested target already exists" : 211,
    "Data source type does not support file attributes" : 212,
    "Could not determine uncompressed file size" : 213,
    "Failed to shrink memory allocation" : 214,
    "name already exists" : 215,
    "Table already exists" : 216,
    "Invalid command. Could not find matching quotes" : 217,
    "Failed to compute the range partition hash function" : 218,
    "Field name cannot be blank" : 219,
    "No data dictionary defined for format type" : 220,
    "Could not find BTree associated with table handle" : 221,
    "BTree key type does not match insert message key type" : 222,
    "BTree dataset identifier does not match insert message dataset identifier" : 223,
    "Command is still running" : 224,
    "Invalid result set ID" : 225,
    "Cannot set position to beyond result set size" : 226,
    "Table is in use right now and cannot be deleted" : 227,
    "One of the lines in the CLI is too long" : 228,
    "Encountered an error reading from file" : 229,
    "Invalid table name" : 230,
    "Namespace name is too long" : 231,
    "Unexpected end-of-file attempting to read from socket" : 232,
    "stats group ID is invalid" : 233,
    "stats group name is invalid" : 234,
    "Invalid handle" : 235,
    "Error communicating across thrift connection" : 236,
    "Malformed BTree. BTree has no root" : 237,
    "Could not find key in BTree" : 238,
    "Could not find key-value pair" : 239,
    "Malformed eval string" : 240,
    "Could not find function" : 241,
    "Wrong number of arguments passed to function" : 242,
    "The new field name is too long" : 243,
    "The field name you entered already exists" : 244,
    "Wrong number of operands provided to operator" : 245,
    "Operation requires 1 operand" : 246,
    "Operation is not supported on input type" : 247,
    "Divide by zero error" : 248,
    "Operation returned NaN" : 249,
    "Mixed type is not supported in this xdf" : 250,
    "Aggregate output has insufficient size to store the result" : 251,
    "KV not found in table" : 252,
    "Listen to: Pretty Vacant by Sex Pistols" : 253,
    "Xdb is vacant" : 254,
    "Xdb is loading data" : 255,
    "Stale XdbHandle, Xdb not found" : 256,
    "Xdb cursor is uninitialized" : 257,
    "Task(s) failed" : 258,
    "The query ID does not exist" : 259,
    "There is no query job associate with this ID" : 260,
    "The query job is currently running" : 261,
    "API Task Failed" : 262,
    "The source table is already indexed by the specified key" : 263,
    "Some variables are undefined during evaluation" : 264,
    "The destination key/value buffer was full" : 265,
    "The module is not initialized yet" : 266,
    "Maximum number of joined values exceeded" : 267,
    "Xdb key type is already set" : 268,
    "Join keys must be of the same data type" : 269,
    "Joins may only be performed on tables with the same DHT" : 270,
    "Failed" : 271,
    "FileName entered is illegal" : 272,
    "File contents are empty" : 273,
    "Eval string entered is too long" : 274,
    "Table has been deleted" : 275,
    "Cant open the file" : 276,
    "Query failed" : 277,
    "Batch Query needs to run in new session" : 278,
    "Failed to create a DAG node" : 279,
    "Failed to delete a DAG node" : 280,
    "Failed to rename a DAG node" : 281,
    "Failed to change the state of DAG node" : 282,
    "No such field found while running aggregate" : 283,
    "Local function requires argument" : 284,
    "Accumulator is not inited" : 285,
    "Return value of aggregate is not a scalar" : 286,
    "Maximum number of tables and datasets reached" : 287,
    "Namespace name is in use" : 288,
    "Bad name for Namespace" : 289,
    "Name not found in Namespace" : 290,
    "Could not find dag node" : 291,
    "Update operation not supported" : 292,
    "Message response size would exceed maximum message payload size" : 293,
    "The requested key was not found" : 294,
    "The requested key's value doesn't equal the provided value" : 295,
    "Could not get amount of memory consumed" : 296,
    "No valid status received!" : 297,
    "No such aggregate operator!" : 298,
    "timed out waiting for table key type to resolve" : 299,
    "Variable name in evalString too long" : 300,
    "DAG handle not found" : 301,
    "DAG name is invalid" : 302,
    "DAG name is too long" : 303,
    "DAG name already exists" : 304,
    "DAG is empty" : 305,
    "DAG is not empty" : 306,
    "No more DAG nodes available" : 307,
    "DAG handle is not available" : 308,
    "DAG Node is currently in use" : 309,
    "DAG Node is in error state" : 310,
    "Operation not supported on the target" : 311,
    "DAG node is not ready" : 312,
    "Fail to destroy DAG handle" : 313,
    "Dataset has been loaded" : 314,
    "Dataset is not ready" : 315,
    "Session does not exist" : 316,
    "Session already exists" : 317,
    "Target session was not inactive" : 318,
    "Session user name is invalid" : 319,
    "Session has an unrecoverable error" : 320,
    "This user's session is present on another node" : 321,
    "The delete operation is not permitted" : 322,
    "Failed to load user-defined module/application" : 323,
    "A module with the given name already exists" : 324,
    "The specified user-defined module/application was not found" : 325,
    "The given module contains no functions" : 326,
    "Module name is invalid" : 327,
    "Module type is invalid" : 328,
    "Module source is invalid" : 329,
    "Module source is too large" : 330,
    "Failed to load function" : 331,
    "The specified function was not found in the given module" : 332,
    "Scalar Function name exceeds allowed length" : 333,
    "Scalar Function has too many parameters" : 334,
    "User-defined function/application variable or parameter name exceeds allowed length" : 335,
    "Variable type not supported by user-defined function/application" : 336,
    "Persisted user-defined function/application is invalid" : 337,
    "Failed to convert value to python data type" : 338,
    "Failed to execute user-defined function/application" : 339,
    "Invalid argument passed to user-defined function/application" : 340,
    "Failed to delete user-defined function/application on all nodes" : 341,
    "Token name in evalString is too long" : 342,
    "No configuration file specified" : 343,
    "Could not resolve result set schema" : 344,
    "DHT name is empty" : 345,
    "Upper bound is less than lower bound" : 346,
    "Checksum validation failed while reading log entry" : 347,
    "DHT chosen doesn't preserve sorted order!" : 348,
    "Maximum log entry size exceeded" : 349,
    "Log entry header is corrupt" : 350,
    "Log format not as expected" : 351,
    "Unrecognized log version" : 352,
    "Invalid KvStore key character" : 353,
    "System DHTs may not be modified" : 354,
    "The requested KvStore doesn't exist" : 355,
    "The CPU does not support Intel SSE 4.2 instructions" : 356,
    "Illegal character in user-defined function/application name" : 357,
    "License data is invalid" : 358,
    "Error opening the file" : 359,
    "Error reading the file" : 360,
    "Error writing the file" : 361,
    "The public key needed to validate the Xcalar license has not been properly provided" : 362,
    "The public key needed to validate the Xcalar license has an error." : 363,
    "The id of the public key needed to validate the Xcalar license is out of range." : 364,
    "The Xcalar license has not been properly provided" : 365,
    "The Xcalar license has an error." : 366,
    "The signature of the Xcalar license is invalid" : 367,
    "The signature of the Xcalar license failed Base32 unmapping" : 368,
    "The data in the Xcalar license failed Base32 decoding" : 369,
    "The checksum of the Xcalar license is invalid" : 370,
    "An unknown error occurred during decoding of the Xcalar license key" : 371,
    "Xcalar license is invalid for this product" : 372,
    "Xcalar license file is too big, or too small" : 373,
    "Xcalar license has expired" : 374,
    "Xcalar license version is too old. Please obtain an updated version." : 375,
    "The Xcalar Cluster has more nodes than the license allows" : 376,
    "The log file was already closed" : 377,
    "The log handle is not valid" : 378,
    "The cluster is in the process of shutting down" : 379,
    "Chosen ordering is not supported" : 380,
    "Failed to connect to HDFS volume" : 381,
    "Failed to get HDFS directory listing" : 382,
    "Available area is too small to render graph" : 383,
    "Mismatch between parameter type and node type" : 384,
    "The Parameter is too long" : 385,
    "Scheduled time may not exceed one year" : 386,
    "Scheduled period may not exceed one year" : 387,
    "The selected API is not parameterizable" : 388,
    "Could not find query record associated with the query id" : 389,
    "Joins may only be performed on tables with the same ordering" : 390,
    "Invalid user cookie provided" : 391,
    "Too many scheduled tasks" : 392,
    "Row has not been completely demystified" : 393,
    "Input is too large" : 394,
    "Failed to parse Xcalar configuration file" : 395,
    "The node ID is invalid" : 396,
    "There are no local nodes in the confiruation file" : 397,
    "Data source type does not support fallocate" : 398,
    "No file extension" : 399,
    "Export target is not supported" : 400,
    "Invalid creation rule specified" : 401,
    "No columns specified for export" : 402,
    "Too many columns specified for export" : 403,
    "Specified column name too long" : 404,
    "Empty result set cannot be exported" : 405,
    "Export requires a known schema" : 406,
    "Export file already exists" : 407,
    "Export file doesn't exist" : 408,
    "Monitor port number is invalid" : 409,
    "Export file and directory both exist with the same base name" : 410,
    "Files were corrupted during export" : 411,
    "Export file requires a new file be created" : 412,
    "Specified max export file size too small" : 413,
    "Cannot export to a single file while specifying header should be separate" : 414,
    "Cannot export append with a separate header file" : 415,
    "Cannot export append to a single file while adding a header" : 416,
    "Invalid header type specified" : 417,
    "Invalid split type specified" : 418,
    "Specified max file size must be greater than 0" : 419,
    "File version is unsupported" : 420,
    "Detected a file corruption" : 421,
    "An invalid request was sent to Xcalar" : 422,
    "Error occurred when using libarchive" : 423,
    "Failed to initialize send socket" : 424,
    "Node was skipped due to a previous error" : 425,
    "Field value truncated during cast" : 426,
    "Cast operation failed" : 427,
    "Log buffer is not aligned" : 428,
    "String encoding not supported" : 429,
    "Messaging interface with other process has been closed" : 430,
    "Operation has finished" : 431,
    "Operation statistics are not avaiable" : 432,
    "Failed to parse batch dataflow file" : 433,
    "Too many columns specified for batch dataflow" : 434,
    "Successfully overwrote user-defined module/application" : 435,
    "Support bundle generation failed" : 436,
    "Message payload too large to fit within message" : 437,
    "No childnode is available to process the operation" : 438,
    "Child process terminated" : 439,
    "Number of pages in an Xdb slot exceeds max extent sg elements" : 440,
    "Could not find aggregate result" : 441,
    "Maximum row size was exceeded" : 442,
    "Maximum directory depth exceeded" : 443,
    "Failed to open subdirectory" : 444,
    "Invalid dataset name provided" : 445,
    "Max statistics group size was exceeded" : 446,
    "Duplicate user-defined field found" : 447,
    "Type conversion error" : 448,
    "Operation not supported in prod build" : 449,
    "Out of available fault injection module slots" : 450,
    "No such errorpoint module" : 451,
    "No such errorpoint" : 452,
    "All specified files empty" : 453,
    "Stats group name too long" : 454,
    "Stats name too long" : 455,
    "Max statistics number was exceeded" : 456,
    "Stats group is full" : 457,
    "No files matching name pattern" : 458,
    "Invalid fatptr prefix or field name" : 459,
    "Duplicated immediate name" : 460,
    "Duplicated fatptr prefix" : 461,
    "List files is not supported for this source type" : 462,
    "Load done already called on this xdb" : 463,
    "Skip records must be specified with a record delimiter" : 464,
    "Parent process has terminated" : 465,
    "Replay session failed" : 466,
    "stack size is less than 2MB" : 467,
    "Target does not exist" : 468,
    "ODBC based database connections must be removed outside Xcalar" : 469,
    "Functional test disabled in this build" : 470,
    "Too many functional tests requested" : 471,
    "Target log corrupted" : 472,
    "Failed to convert from Python object to Xcalar type" : 473,
    "HDFS does not support read/write files" : 474,
    "No tables left in sessionGraph" : 475,
    "The table is empty" : 476,
    "Input regular expression is invalid" : 477,
    "User-defined function/application not found" : 478,
    "Too many outstanding APIs, try again later" : 479,
    "The supplied user name is not within the allowed size range" : 480,
    "Failed to inject Python module" : 481,
    "Invalid initialization" : 482,
    "Failed to parse user defined file list" : 483,
    "Invalid load arguments" : 484,
    "All work has been done." : 485,
    "This user-defined function/application already exists. Delete before adding" : 486,
    "Too few parameters were passed to a user-defined function/application" : 487,
    "The reference count of the operation is incorrect" : 488,
    "Application name is invalid" : 489,
    "Application host type is invalid" : 490,
    "Application is too large" : 491,
    "Transaction recovery context initialization error" : 492,
    "Transaction recovery context default status" : 493,
    "Transaction recovery context was not found" : 494,
    "Transaction recovery resource is not being tracked" : 495,
    "Transaction recovery context state does not allow the requested operation" : 496,
    "Invalid GVM action" : 497,
    "Global variable provided does not exists" : 498,
    "OutputSize was corrupted" : 499,
    "Dataset name already exists" : 500,
    "Dataset has already been deleted" : 501,
    "Batch dataflow does not exist" : 502,
    "Dht specified does not exist" : 503,
    "Table specified does not exist" : 504,
    "Too many parameters in batch dataflow" : 505,
    "This parameter cannot be changed online" : 506,
    "Error occurs during Operation" : 507,
    "Operation has been cancelled" : 508,
    "The query name does not exist" : 509,
    "Parent node does not exist" : 510,
    "Load Application does not exist" : 511,
    "Failed to parse load application output" : 512,
    "Fault injection point triggered" : 513,
    "Fault injection set in 2 phase commit" : 514,
    "Export Application does not exist" : 515,
    "Session user currently in use" : 516,
    "Out of resources (Xcalar Managed Memory)" : 517,
    "App flags invalid" : 518,
    "Query job is already running" : 519,
    "Unknown Message for two PC barrier" : 520,
    "Timed out during cluster startup / shutdown synchronization" : 521,
    "Configured limit on child processes has been reached" : 522,
    "Limit on files loaded has been reached" : 523,
    "Resource temporarily unavailable, try again later" : 524,
    "Cannot export append to a single file with adding a header" : 525,
    "Cannot call an aggregate function during filter/map" : 526,
    "Dag node has been dropped" : 527,
    "Xdb slot has active cursor" : 528,
    "Failed to decode protobuf message" : 529,
    "Failed to load application" : 530,
    "XPU App does not exist" : 531,
    "Path is not on shared storage" : 532,
    "Failed to encode protobuf message" : 533,
    "JSON error occurred" : 534,
    "Message stream not found" : 535,
    "Value too small for defined data type" : 536,
    "No space left in page cache" : 537,
    "SchedTask functionality not supported anymore" : 538,
    "Operation disallowed as object is marked for removal" : 539,
    "Failed to extract output from application" : 540,
    "Failed to extract error message from application" : 541,
    "Inconsistency found in name space internal table" : 542,
    "Stale name space handle" : 543,
    "Invalid use of uninitialized handle" : 544,
    "Durable version not supported" : 545,
    "Durable data written by build from unclean workspace" : 546,
    "Maximum field size was exceeded" : 547,
    "The query name already exists" : 548,
    "Scalar Function module currently in use" : 549,
    "Target currently in use" : 550,
    "Cannot inactivate session, operations outstanding" : 551,
    "The DHT already exists" : 552,
    "The DHT is currently in use" : 553,
    "Number of result sets exceeded table meta limit" : 554,
    "The batch dataflow already exists" : 555,
    "The batch dataflow is currently in use" : 556,
    "Failed to compress buffer" : 557,
    "Failed to decompress buffer" : 558,
    "The query name is invalid" : 559,
    "The query has already already deleted" : 560,
    "The query is currently in use" : 561,
    "XDB serialization error" : 562,
    "XDB deserialization error" : 563,
    "XDB unexpectedly resident" : 564,
    "XDB unexpectedly not resident" : 565,
    "Session already inactivated" : 566,
    "Session is inactive" : 567,
    "Session user already deleted" : 568,
    "Session user does not exist" : 569,
    "Insufficient privilege to shutdown cluster" : 570,
    "Nothing available to serialize" : 571,
    "App with the given name already exists" : 572,
    "App specified was not found" : 573,
    "App currently in use" : 574,
    "Invalid stream context received" : 575,
    "Invalid number of bytes sent in payload" : 576,
    "Encountered partial failure in stats stream, cleaning up" : 577,
    "Log level is too large" : 578,
    "Client performed a handshake we didn't understand" : 579,
    "Query's metadata is on another node. Please go to that node" : 580,
    "App instance start error" : 581,
    "Timed out waiting for api" : 582,
    "IP address is too long" : 583,
    "Support bundle was created but not sent to Xcalar" : 584,
    "Encountered invalid stream protocol, cleaning up" : 585,
    "Encountered partial failure in blob stream, cleaning up" : 586,
    "Encountered unknown format in /proc/meminfo" : 587,
    "API received has invalid signature" : 588,
    "API received has invalid length" : 589,
    "LMDB Key/Value store error" : 590,
    "No buffers to receive on destination XPU" : 591,
    "Invalid ordering for Join" : 592,
    "Dataset is already locked" : 593,
    "XCE node alive, reap timed out" : 594,
    "Attempt to buffer logs failed" : 595,
    "Failure to unbuffer logs is fatal" : 596,
    "Failure in updating periodic log flushing" : 597,
    "The specified log level is not valid" : 598,
    "There are no users of the dataset" : 599,
    "Error parsing JSON query" : 600,
    "Required XEM configuration parameters not present" : 601,
    "Out of dataset memory" : 602,
    "Table is empty" : 603,
    "User info inaccessible since user initialization still in progress" : 604,
    "Target session was not active" : 605,
    "User failed to read sessions" : 606,
    "Generic protobuf error" : 607,
    "Record errors are disallowed" : 608,
    "Cannot replace key field" : 609,
    "Serialization is disabled" : 610,
    "Number of fields exceeded limit" : 611,
    "Wrong number of operands provided to operator" : 612,
    "Missing XcalarOpCode column" : 613,
    "Missing XcalarRankOver column" : 614,
    "XcalarOpCode column contains an invalid value" : 615,
    "XcalarRankOver column contains an invalid value" : 616,
    "Runtime parameters are invalid" : 617,
    "Invalid publish table name" : 618,
    "Publish table name already exists" : 619,
    "An unlicensed feature is in use" : 620,
    "The private key needed to sign the Xcalar license has not been properly provided" : 621,
    "The private key needed to sign the Xcalar license has an error" : 622,
    "The password needed to sign the Xcalar license is missing" : 623,
    "The Xcalar license is empty" : 624,
    "The Xcalar license signature is empty" : 625,
    "License file is bigger than internal buffer" : 626,
    "The password used to verify the license is not correct" : 627,
    "A license value is out of range" : 628,
    "Zlib initialization for the license failed during decompress" : 629,
    "An error occurred while decompressing the license" : 630,
    "The uncompressed license is too large" : 631,
    "Zlib initialization for the license failed during compress" : 632,
    "The specified operation on the license is not supported" : 633,
    "The specified operation has been disabled, because a proper license has not been provided or has expired" : 634,
    "Invalid workbook version" : 635,
    "Publish table name not found" : 636,
    "Publish table update not found" : 637,
    "An upgrade using the Xcalar upgrade tool is required" : 638,
    "Scalar Functions are not supported as part of filter condition in cross joins" : 639,
    "Invalid name supplied for the batch dataflow" : 640,
    "Serialization disabled due to missing serialization path" : 641,
    "Token name in evalString is invalid" : 642,
    "Function does not support array input" : 643,
    "Failed to thick allocate Buffer Cache due to out of memory" : 644,
    "Deserialization encountered an unknown IDL SHA" : 645,
    "Deserialization encountered wrong IDL version" : 646,
    "Incomplete session list (failed to read some sessions)" : 647,
    "Table being activated is dependent on inactive table" : 648,
    "Publish table is restoring" : 649,
    "Update requires a self select" : 650,
    "Required session name is missing" : 651,
    "XPU connection aborted due to internal error, try again later" : 652,
    "Publish table permission denied, since update is being attempted by non-owner Session" : 653,
    "Publish table permission denied, since coalesce is being attempted by non-owner Session" : 654,
    "Publish table owner node does not match the expected node" : 655,
    "Denied reference to Namespace object" : 656,
    "Checksum not found" : 657,
    "Checksum mismatch" : 658,
    "Invalid parameter for setting Runtime configuration" : 659,
    "Setting Runtime configuration not supported" : 660,
    "Publish table Snapshot is already in progress" : 661,
    "Scalar Function API invoked on non-owner node" : 662,
    "Scalar Function source has unexpected contents" : 663,
    "Scalar Function update failure during persistent write" : 664,
    "Scalar Function path not recognized" : 665,
    "Dataset metadata doesn't exist" : 666,
    "Dataset is already unloaded" : 667,
    "Scalar Function module name must be full path name" : 668,
    "Cgroups APIs have been disabled" : 669,
    "Cgroups App already in progress" : 670,
    "Error in JSON during session serialization" : 671,
    "Possible inconsistency in session metadata" : 672,
    "Setting Runtime configuration already in progress" : 673,
    "Limit for select number of rows reached" : 674,
    "Legacy target is not found" : 675,
    "Decimal floating point (DFP/Numeric) error" : 676,
    "Cgroup App already in progress" : 677,
    "Invalid KvStore key" : 678,
    "Invalid KvStore value" : 679,
    "Complex types in Parquet not supported" : 680,
    "Error parsing parquet file" : 681,
    "Unsupported Decimal type in Parquet" : 682,
    "Unsupported Logical type in Parquet Byte Array" : 683,
    "KVStore Ref Count Leak detected" : 684,
    "Pinned and cannot be dropped" : 685,
    "Already pinned" : 686,
    "Not pinned to unpin it" : 687,
    "Defered Free of XDB page header" : 688,
    "Dag node has invalid number of parents" : 689,
    "Invalid table name" : 690,
    "Table name already exists" : 691,
    "Table name not found" : 692,
    "Map failure summary update failed due to schema" : 693,
    "Map failure summary update not supported yet for failures in multiple eval strings" : 694,
    "Scalar Function execution failed in map ICV mode" : 695,
    "Mismatch in column name" : 696,
    "Mismatch in column type" : 697,
    "Mismatch in keys" : 698,
    "Mismatch in key name" : 699,
    "Mismatch in key type" : 700,
    "DHT mismatch" : 701,
    "Disallowed Rankover column in schema" : 702,
    "Disallowed OpCode column in schema" : 703,
    "Disallowed BatchId column in schema" : 704,
    "Disallowed Fatptr in schema" : 705,
    "Invalid Delta table schema" : 706,
    "Invalid table keys" : 707,
    "Starting cluster is still in progress, Retry" : 708,
    "No Cgroup Controller Paths Set -- XCE_CHILDNODE_PATHS does not exist" : 709,
    "Cgroup Controller Path Too Long" : 710,
    "Mismatch in ordering" : 711,
    "Table is in used by IMD and being locked" : 712,
    "Cannot have more than one export to table operation" : 713,
    "Mismatch in column position" : 714,
    "XDB page refcount error" : 715,
    "Stats collection of dataflow is in progress" : 716,
    "Table Id not found" : 717,
    "Invalid fully qualified table name" : 718,
    "Scalar Function create/update succeeded but flush failed" : 719,
    "Table not marked global" : 720,
    "Failed to parse string field length" : 721,
    "Failed to parse bool field" : 722,
    "Failed to parse int32 field" : 723,
    "Failed to parse int64 field" : 724,
    "Failed to parse uint32 field" : 725,
    "Failed to parse uint64 field" : 726,
    "Failed to parse float32 field" : 727,
    "Failed to parse float64 field" : 728,
    "Failed to parse Timestamp field" : 729,
    "Failed to parse numeric field" : 730,
    "Failed to parse proto value field length" : 731,
    "Failed to parse proto value field" : 732,
    "Invalid field type" : 733,
    "System app is disabled" : 734,
    "Union keys must be of the same data type" : 735,
    "Union may only be performed on tables with the same DHT" : 736,
    "Application is still in running state" : 737,
    "Max columns found for schema" : 738,
    "Encountered an internal error - please contact Xcalar support" : 739,
    "Value returned by Scalar Function exceeds maximum Xcalar field size" : 740,
    "A Scalar Function must always return a non None value" : 741,
    "The return type annotation in your Scalar Function <> is an unsupported data type. Supported data types are: bytes, bool, int, float." : 742,
    "Scalar Function with 'bool' return type returning non-'bool' value" : 743,
    "Scalar Function with 'bytes' return type failed due to conversion or resource failure while trying to return the result" : 744,
    "Scalar Function tried to return a value with unsupported type" : 745
}

